# Use an official Python runtime as a parent image
FROM python:3.8

# Set the working directory to /app
WORKDIR /app

# Clone the repository
RUN git clone https://github.com/Li-HsuanChien/Online_course_app.git

# Navigate to the project directory
WORKDIR /app/Online_course_app

# Set up a virtual environment (optional but recommended)
RUN python -m venv venv

# Activate the virtual environment
# On Windows
RUN venv\Scripts\activate
# On Linux/macOS
# RUN source venv/bin/activate

# Install the required dependencies
RUN pip install -U -r requirements.txt

# Expose the port that the app will run on
EXPOSE 8000

# Run the application
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
