# Use an official Python runtime as a parent image
FROM python:3.8

# Set the working directory to /app
WORKDIR /app

# Copy all files
COPY . /app

# Install the required dependencies
RUN pip install -U -r requirements.txt

# Make migrations for DB
RUN python manage.py makemigrations
RUN python manage.py migrate

# Expose the port that the app will run on
EXPOSE 8000

# Run the application
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
